name: Docker Image CI for GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u Anthony-N-Kamau --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/anthony-n-kamau/docker-practice:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/anthony-n-kamau/docker-practice:latest
